### ISSUE TITLE
Shell crashes on Unicode characters

### ISSUE THREAD

**Issue by akston** [mk23/webhdfs#40]
```
Traceback (most recent call last):
  File "/usr/bin/webhdfs", line 75, in <module>
    WebHDFSPrompt(args.url, args.cfg, args.cwd, args.cmd, args.timeout).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/dist-packages/webhdfs/prompt.py", line 227, in do_ls
    self._list_dir(self.hdfs.ls(path))
  File "/usr/lib/python2.7/dist-packages/webhdfs/prompt.py", line 60, in _list_dir
    text = build.get(name, '{}').format(getattr(item, name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 12: ordinal not in range(128)
```

**Comment by mk23** [comment]
Repro case:
```python
>>> f = open(u'test_file_\xe5_name', 'w')
>>> f.write('test\n')
>>> f.close()
```

```
$ hdfs dfs -put test_file_å_name /user/max
```

```
$ PYTHONPATH=$(pwd) ./bin http://localhost:50070/user/max -- ls /user/max
Traceback (most recent call last):
  File "./bin", line 75, in <module>
    WebHDFSPrompt(args.url, args.cfg, args.cwd, args.cmd, args.timeout).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/max/Work/test_webhdfs/webhdfs/prompt.py", line 227, in do_ls
    self._list_dir(self.hdfs.ls(path))
  File "/home/max/Work/test_webhdfs/webhdfs/prompt.py", line 60, in _list_dir
    text = build.get(name, '{}').format(getattr(item, name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 10: ordinal not in range(128)
```

**Comment by mk23** [comment]
After fix:
```
$ PYTHONPATH=$(pwd) ./bin http://localhost:50070/user/max -- ls /user/max
drwxr-xr-x 0 max test       0 Dec 13 2017 17:38:11 sync             
-rw-r--r-- 3 max test       5 Dec 14 2017 10:11:45 test_file_å_name
```

**Comment by mk23** [comment]
Silently breaks completions as well which requires a separate fix.

**Comment by mk23** [comment]
Moving all fixes to `attrib.py` to be universal for all clients.

**Comment by mk23** [comment]
This will require a documentation fix since all attributes will now return strings instead of combination `unicode` and `str`.
