### ISSUE TITLE
WebHDFSIllegalArgumentError not found

### ISSUE THREAD

**Issue by mk23** [mk23/webhdfs#54]
```
Traceback (most recent call last):
  File "/usr/bin/webhdfs", line 71, in <module>
    WebHDFSPrompt(args.url, args.cfg, args.cwd, args.cmd, args.timeout).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/lib/python2.7/dist-packages/webhdfs/prompt.py", line 292, in do_du
    print self.hdfs.du(path, args[1] if len(args) == 2 else 'hdfs_usage')
  File "/usr/lib/python2.7/dist-packages/webhdfs/client.py", line 192, in du
    raise WebHDFSIllegalArgumentError('\'%s\' is an invalid summary attribute' % real)
NameError: global name 'WebHDFSIllegalArgumentError' is not defined
```

**Comment by mk23** [comment]
Duplicate of #52.
